config/routes.rb
Rails.application.routes.draw do
  resources :reserveds
  resources :contacts
  resources :packages

  root 'page#index'
  get 'tentang-kami', to: 'page#index'
  get 'tour-package', to: 'packages#index'
  get 'contact', to: 'contacts#index'
  get 'Reserve', to: 'reserve#new'
  
end

app/models/reserved.rb
class Reserved < ApplicationRecord
end

app/controllers/reserveds_controller.rb
class ReservedsController < ApplicationController
  before_action :set_reserved, only: [:show, :edit, :update, :destroy]

  # GET /reserveds
  # GET /reserveds.json
  def index
    @reserveds = Reserved.all
  end

  # GET /reserveds/1
  # GET /reserveds/1.json
  def show
  end

  # GET /reserveds/new
  def new
    @reserved = Reserved.new
  end

  # GET /reserveds/1/edit
  def edit
  end

  # POST /reserveds
  # POST /reserveds.json
  def create
    @reserved = Reserved.new(reserved_params)

    respond_to do |format|
      if @reserved.save
        format.html { redirect_to @reserved, notice: 'Reserved was successfully created.' }
        format.json { render :show, status: :created, location: @reserved }
      else
        format.html { render :new }
        format.json { render json: @reserved.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /reserveds/1
  # PATCH/PUT /reserveds/1.json
  def update
    respond_to do |format|
      if @reserved.update(reserved_params)
        format.html { redirect_to @reserved, notice: 'Reserved was successfully updated.' }
        format.json { render :show, status: :ok, location: @reserved }
      else
        format.html { render :edit }
        format.json { render json: @reserved.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reserveds/1
  # DELETE /reserveds/1.json
  def destroy
    @reserved.destroy
    respond_to do |format|
      format.html { redirect_to reserveds_url, notice: 'Reserved was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_reserved
      @reserved = Reserved.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def reserved_params
      params.require(:reserved).permit(:name, :email, :pax, :address, :KTP, :title)
    end
end

app/helpers/reserveds_helper.rb
module ReservedsHelper
end

app/views/reserveds/_form.html.erb
<head>
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
<%= form_with(model: reserved, local: true) do |form| %>
  <% if reserved.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(reserved.errors.count, "error") %> prohibited this reserved from being saved:</h2>

      <ul>
      <% reserved.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<style>
body {
  background-image: url("PictFirst.png");
}

* {
  box-sizing: border-box;
}
.row {
  display: -ms-flexbox; /* IE10 */
  display: flex;
  -ms-flex-wrap: wrap; /* IE10 */
  flex-wrap: wrap;
  margin: 0 -16px;
}

.col-25 {
  -ms-flex: 25%; /* IE10 */
  flex: 25%;
}

.col-50 {
  -ms-flex: 50%; /* IE10 */
  flex: 50%;
}

.col-75 {
  -ms-flex: 75%; /* IE10 */
  flex: 75%;
}

.col-25,
.col-50,
.col-75 {
  padding: 0 16px;
}

.container {
  padding: 5px 20px 15px 20px;
  border: 1px solid lightgrey;
  border-radius: 3px;
  float: right;
  margin-right: 35px;
  margin-top: 30px;
  max-width: 500px;
  background-color: black;
  color: white;
}

input[type=text] {
  width: 100%;
  margin-bottom: 20px;
  padding: 12px;
  border: 1px solid #ccc;
  border-radius: 3px;
}

label {
  margin-bottom: 10px;
  display: block;
}

.btn {
  background-color: #4CAF50;
  color: white;
  padding: 12px;
  margin: 10px 0;
  border: none;
  width: 100%;
  border-radius: 3px;
  cursor: pointer;
  font-size: 17px;
}

.btn:hover {
  background-color: #45a049;}
/* Responsive layout - when the screen is less than 800px wide, make the two columns stack on top of each other instead of next to each other (also change the direction - make the "cart" column go on top) */
 @media (max-width: 800px;) {
  .row {
    flex-direction: column-reverse;
  }
}


</style>

</head>

<body>

<div class="row">
  <div class="col-75">
    <div class="container w3-opacity">
    <div class="row">
      <div class="col-50">

         <div class="field">
           <%= form.label :name %>
           <%= form.text_field :name %>
         </div>

          <div class="field">
            <%= form.label :email %>
            <%= form.text_field :email %>
         </div>

           <div class="field">
             <%= form.label :address %>
             <%= form.text_field :address %>
          </div>
  
           <div class="field">
             <%= form.label :pax %>
             <%= form.number_field :pax %>
           </div>
            <%= form.submit %> 
          </div>
     </div>
     </div>
  </div>
 </div> 

<% end %>
</body>
<br>
<br>
<div class="w3-content w3-container w3-center" id="about">
<button class="w3-button w3-black w3-round-large"><a href="/tour-package">Back, see another tour package</a></button>
<br>
<br>
<footer class="w3-center w3-padding-64 w3-black w3-hover-opacity-off"style= "background-color: RGB(0,179,148); color:white">
  <a href="#home" class="w3-button w3-light-grey"><i class="fa fa-arrow-up w3-margin-right"></i>To the top</a>
  <div class="w3-xlarge w3-section">
    <i class="fa fa-facebook-official w3-hover-opacity"></i>
    <i class="fa fa-instagram w3-hover-opacity"></i>
    <i class="fa fa-snapchat w3-hover-opacity"></i>
    <i class="fa fa-pinterest-p w3-hover-opacity"></i>
    <i class="fa fa-twitter w3-hover-opacity"></i>
    <i class="fa fa-linkedin w3-hover-opacity"></i>
  </div>
  </footer>

app/views/reserveds/edit.html.erb
<h1>Editing Reserved</h1>

<%= render 'form', reserved: @reserved %>

<%= link_to 'Show', @reserved %> |
<%= link_to 'Back', reserveds_path %>

app/views/reserveds/index.html.erb
<p id="notice"><%#= notice %></p>

<h1></h1>

<table>
  <thead>
    <tr>
    </tr>
  </thead>

  <tbody>
    <% @reserveds.each do |reserved| %>
      <tr>
        <td><%= reserved.name %></td>
        <td><%= reserved.email %></td>
        <td><%= reserved.pax %></td>
        <td><%= reserved.address %></td>
        <td><%= reserved.KTP %></td>
        <td><%= reserved.title %></td>
        <td><%= link_to 'Show', reserved %></td>
        <td><%= link_to 'Edit', edit_reserved_path(reserved) %></td>
        <td><%= link_to 'Destroy', reserved, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%#= link_to 'New Reserved', new_reserved_path %>

app/views/reserveds/new.html.erb
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Lato">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">


<style>
body,h1,h2,h3,h4,h5,h6 {font-family: "Lato", sans-serif;}
body, html {
  height: 100%;
  line-height: 1.8;
}
h1 {color:black;
text-align: center;
font-size: 36px;
font: bold;
padding: 5px;
margin-right:20px;
}

.pict{ background-image: url('/assets/liveaboard-raja-ampat-fam-islands-xxl.jpg') }

</style>
</head>
<br>
<br>

<body>
<div class="pict">
<div class="w3-display-top w3-center" style="white-space:nowrap;">
    <span class="w3-center w3-padding-large w3-xlarge w3-black w3-wide w3-animate-opacity" style= "margin-top:50px">New <span class="w3-hide-small">Reserve</span>
  </div>
<!-- Navbar (sit on top) -->
<div class="w3-top"style="background-color:white">
  <div class="w3-bar" id="myNavbar">
    <a class="w3-bar-item w3-button  w3-hide-medium w3-hide-large w3-right" href="javascript:void(0);" onclick="toggleFunction()" title="Toggle Navigation Menu">
      <i class="fa fa-bars"></i>
    </a>
    <a href="/tentang-kami" class="w3-bar-item w3-button">HOME</a>
    <a href="/tour-package" class="w3-bar-item w3-button w3-hide-small"><i class="fa fa-user"></i> TOUR PACKAGE</a>
    <a href="/contact-us" class="w3-bar-item w3-button w3-hide-small"><i class="fa fa-envelope"></i> CONTACT</a>
    </a>
  </div>

  <!-- Navbar on small screens -->
  <div id="navDemo" class="w3-bar-block w3-white w3-hide w3-hide-large w3-hide-medium"style= "background-color: RGB(0,179,148)">
    <a href="#home" class="w3-bar-item w3-button" onclick="toggleFunction()">HOME</a>
    <a href="/tour-package" class="w3-bar-item w3-button" onclick="toggleFunction()">TOUR PACKAGE</a>
    <a href="/contact-us" class="w3-bar-item w3-button" onclick="toggleFunction()">CONTACT</a>
    <a href="#" class="w3-bar-item w3-button">SEARCH</a>
  </div>
</div>

<div class="bgimg-1 w3-display-container w3-opacity-min w3-hover-white" id="home">
  <div class="w3-display-middle" style="white-space:nowrap;">
  </div>
</div>

<%= render 'form', reserved: @reserved %>
</body>

<%#= link_to 'Back', reserveds_path %>
<!-- Footer -->

app/views/reserveds/show.html.erb
<p id="notice"><%= notice %></p>
<head>
</head>

<body>

<div class="w3-display-top w3-center" style="white-space:nowrap;">
    <span class="w3-center w3-padding-large w3-xlarge w3-black w3-wide w3-animate-opacity" style= "margin-top:50px">PULANG <span class="w3-hide-small">PERGI</span> .COM</span>
  </div>

<div class="w3-display-top w3-center w3-padding-64" style="font-size:30px"> Hai,<strong> <%= @reserved.name %> </strong>! </div>
<div class="w3-content w3-container" id="about"> 
<p class="w3-center" style="font-size:24px"><em>Your Great Journey, Strat from Us</em></p>
<p class="w3-center" style="font-size:16px ">Thankyou, for trusting Pulang Pergi. The number of ticket bookings is being processed, check your email, <strong> <%= @reserved.email %> </strong> to see your payment details. We and your ticket are waiting for your payment. Have a nice day<p>
</div>
  <%#= @reserved.name %>
</p>

<p>
  <%#= @reserved.email %>
</p>

<p>
  <%#= @reserved.pax %>
</p>

<p>
  <%#= @reserved.address %>
</p>

<p>
  <%#= @reserved.KTP %>
</p>

<p>
  <%#= @reserved.title %>
</p>

<p class="w3-center"> Whoopps i want to change my reserve! | </p>

<div class="w3-content w3-container w3-center" id="about">
<button class="w3-button w3-black w3-round-large"><a> <%= link_to 'Edit', edit_reserved_path(@reserved) %> </a></button>
<button class="w3-button w3-black w3-round-large"><a href="/tentang-kami">Back</a></button>
</div>