config/routes.rb
Rails.application.routes.draw do
  resources :reserveds
  resources :contacts
  resources :packages

  root 'page#index'
  get 'tentang-kami', to: 'page#index'
  get 'tour-package', to: 'packages#index'
  get 'contact', to: 'contacts#index'
  get 'Reserve', to: 'reserve#new'
  
end

app/models/contact.rb
class Contact < ApplicationRecord
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  before_action :set_contact, only: [:show, :edit, :update, :destroy]

  # GET /contacts
  # GET /contacts.json
  def index
    @contacts = Contact.all
  end

  # GET /contacts/1
  # GET /contacts/1.json
  def show
  end

  # GET /contacts/new
  def new
    @contact = Contact.new
  end

  # GET /contacts/1/edit
  def edit
  end

  # POST /contacts
  # POST /contacts.json
  def create
    @contact = Contact.new(contact_params)

    respond_to do |format|
      if @contact.save
        format.html { redirect_to @contact, notice: 'Contact was successfully created.' }
        format.json { render :show, status: :created, location: @contact }
      else
        format.html { render :new }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /contacts/1
  # PATCH/PUT /contacts/1.json
  def update
    respond_to do |format|
      if @contact.update(contact_params)
        format.html { redirect_to @contact, notice: 'Contact was successfully updated.' }
        format.json { render :show, status: :ok, location: @contact }
      else
        format.html { render :edit }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /contacts/1
  # DELETE /contacts/1.json
  def destroy
    @contact.destroy
    respond_to do |format|
      format.html { redirect_to contacts_url, notice: 'Contact was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_contact
      @contact = Contact.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def contact_params
      params.require(:contact).permit(:Contact)
    end
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/views/contacts/_form.html.erb
<%= form_with(model: contact, local: true) do |form| %>
  <% if contact.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(contact.errors.count, "error") %> prohibited this contact from being saved:</h2>

      <ul>
      <% contact.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<div class="w3-large w3-center w3-section"> 
  <%= form.text_field :Contact %>
  <div class="field"> 
  </div>
  <div class="actions" style="w3-button w3-black w3-round">
    <%= form.submit %>
  </div>
<% end %>
<%#= link_to 'New Package', new_package_path %>

  

app/views/contacts/edit.html.erb
<h1>Editing Contact</h1>

<%= render 'form', contact: @contact %>

<%= link_to 'Show', @contact %> |
<%= link_to 'Back', contacts_path %>

app/views/contacts/index.html.erb
<!DOCTYPE html>
<html>
<title></title>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Lato">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
<style>
body,h1,h2,h3,h4,h5,h6 {font-family: "Lato", sans-serif;}
body, html {
  height: 100%;
  color: #777;
  line-height: 1.8;
}

/* Create a Parallax Effect */
.bgimg-1, .bgimg-2, .bgimg-3 {
  background-attachment: fixed;
  background-position: center;
  background-repeat: no-repeat;
  background-size: cover;
}

/* First image (Logo. Full height) */
.bgimg-1 {
  background-image: url('hong-kong-city-hd-wallpaper.jpg');
  min-height: 100%;
}


.w3-wide {letter-spacing: 10px;}
.w3-hover-opacity {cursor: pointer;}

/* Turn off parallax scrolling for tablets and phones */
@media only screen and (max-device-width: 1600px) {
  .bgimg-1, .bgimg-2, .bgimg-3 {
    background-attachment: scroll;
    min-height: 400px;
  }
  
}
</style>
<body>
<!-- Navbar (sit on top) -->
<div class="w3-top w3-white ">
  <div class="w3-bar" id="myNavbar">
    <a class="w3-bar-item w3-button w3-hover-black w3-hide-medium w3-hide-large w3-right" href="javascript:void(0);" onclick="toggleFunction()" title="Toggle Navigation Menu">
      <i class="fa fa-bars"></i>
    <a href="/tentang-kami" class="w3-bar-item w3-button">HOME</a>
    <a href="/tour-package" class="w3-bar-item w3-button w3-hide-small"><i class="fa fa-user"></i> TOUR PACKAGE</a>
    <a href="/contact-us" class="w3-bar-item w3-button w3-hide-small"><i class="fa fa-envelope"></i> CONTACT</a>
    <a href="/" class="w3-bar-item w3-button w3-hide-small w3-right w3-hover-red">
  </div>


  <!-- Navbar on small screens -->
  <div id="navDemo" class="w3-bar-block w3-white w3-hide w3-hide-large w3-hide-medium"style= "background-color: RGB(0,179,148)">
    <a href="/tentang-kami" class="w3-bar-item w3-button" onclick="toggleFunction()">HOME</a>
    <a href="/tour-package" class="w3-bar-item w3-button" onclick="toggleFunction()">TOUR PACKAGE</a>
    <a href="/contacts/new" class="w3-bar-item w3-button" onclick="toggleFunction()">CONTACT</a>
  </div>
</div>

<!-- First Parallax Image with Logo Text -->
<div class="bgimg-1 w3-display-container w3-opacity-min" id="home">
  <div class="w3-display-middle" style="white-space:nowrap;">
    <span class="w3-center w3-padding-large w3-xlarge w3-black w3-wide w3-animate-opacity" style= "background-color:  RGB(0,179,148)">PULANG <span class="w3-hide-small">PERGI</span> .COM</span>
  </div>
</div>

<!-- Container (About Section) -->
<div class="w3-content w3-container w3-padding-64" id="about">
  <h3 class="w3-center">CONTACT</h3>
  <p class="w3-center"><em>Your Great Journey, Strat from Us</em></p>
  <p>Want to know more about our tour, packages, journey and many more. stay keep in touch with us. leave your email to get our monthly magazine!</p>
   <br>
 
  
  <%#= link_to 'Show', contact %>
  <%#= link_to 'Edit', edit_contact_path(contact) %>
  <%#= link_to 'Destroy', contact, method: :delete, data: { confirm: 'Are you sure?' } %>
  <div class="w3-large w3-center w3-section"> 
  <input><span class="w3-center w3-padding-large w3-xlarge">
   <p><a href="/contacts/new" style="width:100px height:100px">   Subscribe Now!</a></p></div>
</body>

<div class="w3-xlarge w3-center w3-section"> 
    <i class="fa fa-facebook-official w3-hover-opacity w3-xlarge"></i>
    <i class="fa fa-instagram w3-hover-opacity"></i>
    <i class="fa fa-snapchat w3-hover-opacity"></i>
    <i class="fa fa-pinterest-p w3-hover-opacity"></i>
    <i class="fa fa-twitter w3-hover-opacity"></i>
    <i class="fa fa-linkedin w3-hover-opacity"></i>

<footer class="w3-center w3-padding-64 w3-black w3-hover-opacity-off"style= "background-color: RGB(0,179,148); color:white">
  </div>
  </footer>

  <%= link_to 'New Contacts', new_contact_path %>

app/views/contacts/new.html.erb
<!DOCTYPE html>
<html>
<title></title>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Lato">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
<style>
body,h1,h2,h3,h4,h5,h6 {font-family: "Lato", sans-serif;}
body, html {
  height: 100%;
  line-height: 1.8;
}

/* Create a Parallax Effect */
.bgimg-1, .bgimg-2, .bgimg-3 {
  background-attachment: fixed;
  background-position: center;
  background-repeat: no-repeat;
  background-size: cover;
}

/* First image (Logo. Full height) */
.bgimg-1 {
  background-image: url("/assets/SouthKorea.jpg");
  min-height: 100%;
}


.w3-wide {letter-spacing: 10px;}
.w3-hover-opacity {cursor: pointer;}

/* Turn off parallax scrolling for tablets and phones */
@media only screen and (max-device-width: 1600px) {
  .bgimg-1, .bgimg-2, .bgimg-3 {
    background-attachment: scroll;
    min-height: 400px;
  }
  
}
</style>
<body>
<!-- Navbar (sit on top) -->
<div class="w3-top w3-white ">
  <div class="w3-bar" id="myNavbar">
    <a class="w3-bar-item w3-button w3-hover-black w3-hide-medium w3-hide-large w3-right" href="javascript:void(0);" onclick="toggleFunction()" title="Toggle Navigation Menu">
      <i class="fa fa-bars"></i>
    <a href="/tentang-kami" class="w3-bar-item w3-button">HOME</a>
    <a href="/tour-package" class="w3-bar-item w3-button w3-hide-small"><i class="fa fa-user"></i> TOUR PACKAGE</a>
    <a href="/contacts/new" class="w3-bar-item w3-button w3-hide-small"><i class="fa fa-envelope"></i> CONTACT</a>
  </div>


  <!-- Navbar on small screens -->
  <div id="navDemo" class="w3-bar-block w3-white w3-hide w3-hide-large w3-hide-medium"style= "background-color: RGB(0,179,148)">
    <a href="/tentang-kami" class="w3-bar-item w3-button" onclick="toggleFunction()">HOME</a>
    <a href="/tour-package" class="w3-bar-item w3-button" onclick="toggleFunction()">TOUR PACKAGE</a>
    <a href="/contacts/new" class="w3-bar-item w3-button" onclick="toggleFunction()">CONTACT</a>
  </div>
</div>

<!-- First Parallax Image with Logo Text -->
<div class="bgimg-1 w3-display-container w3-opacity-min" id="home">
  <div class="w3-display-middle" style="white-space:nowrap;">
    <span class="w3-center w3-padding-large w3-xlarge w3-black w3-wide w3-animate-opacity" style= "background-color:  RGB(0,179,148)">PULANG <span class="w3-hide-small">PERGI</span> .COM</span>
  </div>
</div>

<!-- Container (About Section) -->
<div class="w3-content w3-container" id="about">
  <h3 class="w3-center">CONTACT</h3>
  <p class="w3-center"><em>Your Great Journey, Strat from Us</em></p>
  <p>Want to know more about our tour, packages, journey and many more. stay keep in touch with us. leave your email to get our monthly magazine!</p>
</div>
  <%= render 'form', contact: @contact %>
  <%#= link_to 'Show', contact %>
  <%#= link_to 'Edit', edit_contact_path(contact) %>
  <%#= link_to 'Destroy', contact, method: :delete, data: { confirm: 'Are you sure?' } %>
</body>

<div class="w3-xlarge w3-center w3-section"> 
    <i class="fa fa-facebook-official w3-hover-opacity w3-xlarge"></i>
    <i class="fa fa-instagram w3-hover-opacity"></i>
    <i class="fa fa-snapchat w3-hover-opacity"></i>
    <i class="fa fa-pinterest-p w3-hover-opacity"></i>
    <i class="fa fa-twitter w3-hover-opacity"></i>
    <i class="fa fa-linkedin w3-hover-opacity"></i>
<footer class="w3-center w3-padding-64 w3-black w3-hover-opacity-off"style= "background-color: RGB(0,179,148); color:white">
  </div>
  </footer>

app/views/contacts/show.html.erb
<p id="notice"><%= notice %></p>


<%#= link_to 'Edit', edit_contact_path(@contact) %> 

<body>

<div class="w3-display-top w3-center" style="white-space:nowrap; margin-top:75px">
    <span class="w3-center w3-padding-large w3-xlarge w3-black w3-wide w3-animate-opacity">PULANG <span class="w3-hide-small">PERGI</span> .COM</span>
  </div>
<br>
<br>

<div class="w3-display-top w3-center" style="font-size:30px"></div>
<div class="w3-content w3-container" id="about"> 
<p class="w3-center" style="font-size:24px"><em>Your Great Journey, Strat from Us</em></p>
<p class="w3-center" style="font-size:16px "> Hai,this email <strong>  <%= @contact.Contact %> </strong> will receive our message as soon as possible :) <p>
<p class="w3-center" style="font-size:16px ">Thankyou, for subscribe Pulang Pergi.  Please keep in touch with us and wait our monthly magsz to explore your package tour<p>
</div>
<br>
<br>

<div class="w3-content w3-container w3-center" id="about">
<button class="w3-button w3-black w3-round-large w3-center"><a href="/tentang-kami">Back Home</a></button>
</div>
</body>